# NAME: John Tran
# EMAIL: johntran627@gmail.com
# UID: 005183495

.SILENT:

default: dist

dist: my_beaglebone.jpg connected.png copy.png build_run.png git.png README Makefile
	tar -czvf lab4a-005183495.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png README Makefile


