# NAME: John Tran
# EMAIL: johntran627@gmail.com
# UID: 005183495

.SILENT:

default:
	rm -f lab3b
	ln -s lab3b.py lab3b
	chmod u+x lab3b
	echo "Compiled successfully"

clean:
	rm -f lab3b-005183495.tar.gz lab3b

dist:
	tar -czvf lab3b-005183495.tar.gz Makefile README lab3b.py 
