# NAME: John Tran
# EMAIL: johntran627@gmail.com
# UID: 005183495

.SILENT:

default: 
	gcc -Wall -Wextra -g -o lab3a lab3a.c

clean:
	rm -f lab3a lab3a-005183495.tar.gz

dist: lab3a
	tar -czvf lab3a-005183495.tar.gz README Makefile lab3a.c ext2_fs.h 
